# fly.toml file generated for utako-discord-bot on 2022-11-23T11:40:29Z

app = "utako-discord-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "docker/Dockerfile.music"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  processes = ["app"]
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
