style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/tktcorporation/discord-speech-bot
options:
  commits:
    filters:
      Type:
        - zap
        - bug
        - fire
        - art
        - white_check_mark
        - sparkles
        - lipstick
        - memo
        - loop
        - bookmark
        - technologist
  commit_groups:
    title_maps:
      zap: Improve performance
      bug: Fix bugs
      fire: Remove code or files
      art: Improve structure / format of the code
      white_check_mark: Add, update, or pass tests
      sparkles: Introduce new features
      lipstick: Add or update the UI and style files
      memo: Add or update documentation
      loop: Change requirements / dependencies
      bookmark: Release / Version tags
      technologist: Improve developer experience
  merges:
    pattern: "(#\\w+)"
    pattern_maps:
      - Source
  issues:
    prefix:
      - /
  header:
    pattern: "^:?(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
