style: github
template: RELEASE.tpl.md
info:
  repository_url: https://github.com/tktcorporation/discord-speech-bot
options:
  commits:
    filters:
      Type:
        - sparkles
        - bug
        - perf
        - refactor
  commit_groups:
    title_maps:
      sparkles: Features
      bug: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      ci: Continuous Integration
  merges:
    pattern: "(#\\w+)"
    pattern_maps:
      - Source
  issues:
    prefix:
      - /
  header:
    pattern: "^:?(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
