name: "HerokuDeployMusic"

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment:
      name: heroku_production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

      - name: Set Env Vars on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku config:set DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN_MUSIC }} DISCORD_CMD_PREFIX=${{ secrets.DISCORD_CMD_PREFIX_MUSIC }} AWS_REGION=${{ secrets.AWS_REGION }} AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} -a ${{ secrets.HEROKU_MUSIC_APP_NAME }}

      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          docker build -f "docker/Dockerfile.music" -t music .
          docker tag music registry.heroku.com/${{ secrets.HEROKU_MUSIC_APP_NAME }}/app
          docker push registry.heroku.com/${{ secrets.HEROKU_MUSIC_APP_NAME }}/app

      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a ${{ secrets.HEROKU_MUSIC_APP_NAME }} app
