name: Light Test

on:
  pull_request:

defaults:
  run:
    shell: bash
    working-directory: ./

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DISCORD_CMD_PREFIX: "~"
  DISCORD_TOKEN: "dummy"

jobs:
  lint:
    name: Rust ${{ matrix.os }} ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        rust:
          - stable
        os: [ubuntu-latest]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      # Cache files between builds
      - name: Setup | Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Install tools
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
          libopus-dev \
          build-essential \
          libssl-dev \
          pkg-config \
          autoconf \
          automake \
          libtool \
          m4 \
          ffmpeg \
          curl \
          python \
          git

          sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/bin/youtube-dl && \
          sudo chmod a+rx /usr/bin/youtube-dl

      - name: test
        run: cargo test --all-features
